<?php

namespace DoctrineProxies\__CG__\EventoOriginal\Core\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Customer extends \EventoOriginal\Core\Entities\Customer implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Customer' . "\0" . 'id', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Customer' . "\0" . 'firstName', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Customer' . "\0" . 'lastName', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Customer' . "\0" . 'websiteName', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Customer' . "\0" . 'websiteUrl', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Customer' . "\0" . 'affiliateCode', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Customer' . "\0" . 'user'];
        }

        return ['__isInitialized__', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Customer' . "\0" . 'id', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Customer' . "\0" . 'firstName', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Customer' . "\0" . 'lastName', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Customer' . "\0" . 'websiteName', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Customer' . "\0" . 'websiteUrl', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Customer' . "\0" . 'affiliateCode', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Customer' . "\0" . 'user'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Customer $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getFirstName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirstName', []);

        return parent::getFirstName();
    }

    /**
     * {@inheritDoc}
     */
    public function setFirstName(string $firstName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFirstName', [$firstName]);

        return parent::setFirstName($firstName);
    }

    /**
     * {@inheritDoc}
     */
    public function getWebsiteName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWebsiteName', []);

        return parent::getWebsiteName();
    }

    /**
     * {@inheritDoc}
     */
    public function getLastName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastName', []);

        return parent::getLastName();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastName(string $lastName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastName', [$lastName]);

        return parent::setLastName($lastName);
    }

    /**
     * {@inheritDoc}
     */
    public function setWebsiteName(string $websiteName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWebsiteName', [$websiteName]);

        return parent::setWebsiteName($websiteName);
    }

    /**
     * {@inheritDoc}
     */
    public function getWebsiteUrl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWebsiteUrl', []);

        return parent::getWebsiteUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function setWebsiteUrl(string $websiteUrl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWebsiteUrl', [$websiteUrl]);

        return parent::setWebsiteUrl($websiteUrl);
    }

    /**
     * {@inheritDoc}
     */
    public function getAffiliateCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAffiliateCode', []);

        return parent::getAffiliateCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setAffiliateCode(string $affiliateCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAffiliateCode', [$affiliateCode]);

        return parent::setAffiliateCode($affiliateCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(\EventoOriginal\Core\Entities\User $user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        return parent::setUser($user);
    }

}
