<?php

namespace DoctrineProxies\__CG__\EventoOriginal\Core\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Payout extends \EventoOriginal\Core\Entities\Payout implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Payout' . "\0" . 'id', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Payout' . "\0" . 'originalAmount', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Payout' . "\0" . 'originalCurrency', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Payout' . "\0" . 'paidAmount', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Payout' . "\0" . 'paidCurrency', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Payout' . "\0" . 'description', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Payout' . "\0" . 'status', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Payout' . "\0" . 'user', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Payout' . "\0" . 'gateway', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Payout' . "\0" . 'requestData', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Payout' . "\0" . 'responseData', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Payout' . "\0" . 'date', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Payout' . "\0" . 'externalId', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Payout' . "\0" . 'refunded'];
        }

        return ['__isInitialized__', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Payout' . "\0" . 'id', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Payout' . "\0" . 'originalAmount', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Payout' . "\0" . 'originalCurrency', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Payout' . "\0" . 'paidAmount', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Payout' . "\0" . 'paidCurrency', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Payout' . "\0" . 'description', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Payout' . "\0" . 'status', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Payout' . "\0" . 'user', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Payout' . "\0" . 'gateway', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Payout' . "\0" . 'requestData', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Payout' . "\0" . 'responseData', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Payout' . "\0" . 'date', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Payout' . "\0" . 'externalId', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Payout' . "\0" . 'refunded'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Payout $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getOriginalAmount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOriginalAmount', []);

        return parent::getOriginalAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function setOriginalAmount(int $originalAmount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOriginalAmount', [$originalAmount]);

        return parent::setOriginalAmount($originalAmount);
    }

    /**
     * {@inheritDoc}
     */
    public function getOriginalCurrency()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOriginalCurrency', []);

        return parent::getOriginalCurrency();
    }

    /**
     * {@inheritDoc}
     */
    public function setOriginalCurrency(string $originalCurrency)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOriginalCurrency', [$originalCurrency]);

        return parent::setOriginalCurrency($originalCurrency);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaidAmount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaidAmount', []);

        return parent::getPaidAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaidAmount(int $paidAmount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaidAmount', [$paidAmount]);

        return parent::setPaidAmount($paidAmount);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaidCurrency()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaidCurrency', []);

        return parent::getPaidCurrency();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaidCurrency(string $paidCurrency)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaidCurrency', [$paidCurrency]);

        return parent::setPaidCurrency($paidCurrency);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription(string $description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus(string $status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(\EventoOriginal\Core\Entities\User $user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getGateway()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGateway', []);

        return parent::getGateway();
    }

    /**
     * {@inheritDoc}
     */
    public function setGateway(string $gateway)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGateway', [$gateway]);

        return parent::setGateway($gateway);
    }

    /**
     * {@inheritDoc}
     */
    public function getRequestData()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRequestData', []);

        return parent::getRequestData();
    }

    /**
     * {@inheritDoc}
     */
    public function setRequestData(string $requestData)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRequestData', [$requestData]);

        return parent::setRequestData($requestData);
    }

    /**
     * {@inheritDoc}
     */
    public function getResponseData()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResponseData', []);

        return parent::getResponseData();
    }

    /**
     * {@inheritDoc}
     */
    public function setResponseData(string $responseData)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setResponseData', [$responseData]);

        return parent::setResponseData($responseData);
    }

    /**
     * {@inheritDoc}
     */
    public function getDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDate', []);

        return parent::getDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setDate(\DateTime $date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDate', [$date]);

        return parent::setDate($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getReceiver()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReceiver', []);

        return parent::getReceiver();
    }

    /**
     * {@inheritDoc}
     */
    public function setReceiver(\EventoOriginal\Core\Entities\User $receiver)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReceiver', [$receiver]);

        return parent::setReceiver($receiver);
    }

    /**
     * {@inheritDoc}
     */
    public function getOriginalMoney()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOriginalMoney', []);

        return parent::getOriginalMoney();
    }

    /**
     * {@inheritDoc}
     */
    public function setOriginalMoney(\Money\Money $originalMoney)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOriginalMoney', [$originalMoney]);

        return parent::setOriginalMoney($originalMoney);
    }

    /**
     * {@inheritDoc}
     */
    public function getExternalId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExternalId', []);

        return parent::getExternalId();
    }

    /**
     * {@inheritDoc}
     */
    public function setExternalId(string $externalId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExternalId', [$externalId]);

        return parent::setExternalId($externalId);
    }

    /**
     * {@inheritDoc}
     */
    public function isRefunded()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isRefunded', []);

        return parent::isRefunded();
    }

    /**
     * {@inheritDoc}
     */
    public function setRefunded(bool $refunded)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRefunded', [$refunded]);

        return parent::setRefunded($refunded);
    }

}
