<?php

namespace DoctrineProxies\__CG__\EventoOriginal\Core\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Payment extends \EventoOriginal\Core\Entities\Payment implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Payment' . "\0" . 'id', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Payment' . "\0" . 'paidDate', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Payment' . "\0" . 'originalAmount', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Payment' . "\0" . 'originalCurrency', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Payment' . "\0" . 'paidAmount', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Payment' . "\0" . 'paidCurrency', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Payment' . "\0" . 'order', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Payment' . "\0" . 'status', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Payment' . "\0" . 'user', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Payment' . "\0" . 'gateway', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Payment' . "\0" . 'requestData', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Payment' . "\0" . 'responseData', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Payment' . "\0" . 'description', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Payment' . "\0" . 'data', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Payment' . "\0" . 'param', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Payment' . "\0" . 'externalId'];
        }

        return ['__isInitialized__', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Payment' . "\0" . 'id', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Payment' . "\0" . 'paidDate', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Payment' . "\0" . 'originalAmount', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Payment' . "\0" . 'originalCurrency', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Payment' . "\0" . 'paidAmount', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Payment' . "\0" . 'paidCurrency', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Payment' . "\0" . 'order', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Payment' . "\0" . 'status', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Payment' . "\0" . 'user', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Payment' . "\0" . 'gateway', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Payment' . "\0" . 'requestData', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Payment' . "\0" . 'responseData', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Payment' . "\0" . 'description', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Payment' . "\0" . 'data', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Payment' . "\0" . 'param', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Payment' . "\0" . 'externalId'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Payment $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getPaidDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaidDate', []);

        return parent::getPaidDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaidDate(\DateTime $date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaidDate', [$date]);

        return parent::setPaidDate($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrder()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrder', []);

        return parent::getOrder();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrder(\EventoOriginal\Core\Entities\Order $order)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrder', [$order]);

        return parent::setOrder($order);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus(string $status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getPayer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPayer', []);

        return parent::getPayer();
    }

    /**
     * {@inheritDoc}
     */
    public function setPayer(\EventoOriginal\Core\Infrastructure\Payments\Interfaces\PayerInterface $payer)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPayer', [$payer]);

        return parent::setPayer($payer);
    }

    /**
     * {@inheritDoc}
     */
    public function getGateway()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGateway', []);

        return parent::getGateway();
    }

    /**
     * {@inheritDoc}
     */
    public function setGateway(string $gateway)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGateway', [$gateway]);

        return parent::setGateway($gateway);
    }

    /**
     * {@inheritDoc}
     */
    public function getOriginalMoney()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOriginalMoney', []);

        return parent::getOriginalMoney();
    }

    /**
     * {@inheritDoc}
     */
    public function setOriginalMoney(\Money\Money $money)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOriginalMoney', [$money]);

        return parent::setOriginalMoney($money);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaidMoney()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaidMoney', []);

        return parent::getPaidMoney();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaidMoney(\Money\Money $money)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaidMoney', [$money]);

        return parent::setPaidMoney($money);
    }

    /**
     * {@inheritDoc}
     */
    public function getRequestData()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRequestData', []);

        return parent::getRequestData();
    }

    /**
     * {@inheritDoc}
     */
    public function setRequestData(array $data)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRequestData', [$data]);

        return parent::setRequestData($data);
    }

    /**
     * {@inheritDoc}
     */
    public function getResponseData()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResponseData', []);

        return parent::getResponseData();
    }

    /**
     * {@inheritDoc}
     */
    public function setResponseData(array $data)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setResponseData', [$data]);

        return parent::setResponseData($data);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription(string $description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getData()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getData', []);

        return parent::getData();
    }

    /**
     * {@inheritDoc}
     */
    public function setData(array $data)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setData', [$data]);

        return parent::setData($data);
    }

    /**
     * {@inheritDoc}
     */
    public function setParams(array $params = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParams', [$params]);

        return parent::setParams($params);
    }

    /**
     * {@inheritDoc}
     */
    public function getParam($key)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParam', [$key]);

        return parent::getParam($key);
    }

    /**
     * {@inheritDoc}
     */
    public function setParam($key, $value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParam', [$key, $value]);

        return parent::setParam($key, $value);
    }

    /**
     * {@inheritDoc}
     */
    public function getParams()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParams', []);

        return parent::getParams();
    }

    /**
     * {@inheritDoc}
     */
    public function getExternalId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExternalId', []);

        return parent::getExternalId();
    }

    /**
     * {@inheritDoc}
     */
    public function setExternalId(string $externalId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExternalId', [$externalId]);

        return parent::setExternalId($externalId);
    }

}
