<?php

namespace DoctrineProxies\__CG__\EventoOriginal\Core\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Article extends \EventoOriginal\Core\Entities\Article implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Article' . "\0" . 'id', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Article' . "\0" . 'name', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Article' . "\0" . 'description', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Article' . "\0" . 'shortDescription', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Article' . "\0" . 'barCode', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Article' . "\0" . 'internalCode', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Article' . "\0" . 'status', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Article' . "\0" . 'price', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Article' . "\0" . 'pricePerQuantity', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Article' . "\0" . 'priceCurrency', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Article' . "\0" . 'tax', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Article' . "\0" . 'costPrice', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Article' . "\0" . 'publishedOn', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Article' . "\0" . 'ingredients', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Article' . "\0" . 'licenses', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Article' . "\0" . 'brand', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Article' . "\0" . 'category', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Article' . "\0" . 'tags', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Article' . "\0" . 'colors', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Article' . "\0" . 'flavours', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Article' . "\0" . 'allergens', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Article' . "\0" . 'translations', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Article' . "\0" . 'slug', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Article' . "\0" . 'images'];
        }

        return ['__isInitialized__', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Article' . "\0" . 'id', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Article' . "\0" . 'name', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Article' . "\0" . 'description', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Article' . "\0" . 'shortDescription', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Article' . "\0" . 'barCode', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Article' . "\0" . 'internalCode', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Article' . "\0" . 'status', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Article' . "\0" . 'price', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Article' . "\0" . 'pricePerQuantity', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Article' . "\0" . 'priceCurrency', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Article' . "\0" . 'tax', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Article' . "\0" . 'costPrice', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Article' . "\0" . 'publishedOn', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Article' . "\0" . 'ingredients', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Article' . "\0" . 'licenses', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Article' . "\0" . 'brand', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Article' . "\0" . 'category', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Article' . "\0" . 'tags', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Article' . "\0" . 'colors', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Article' . "\0" . 'flavours', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Article' . "\0" . 'allergens', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Article' . "\0" . 'translations', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Article' . "\0" . 'slug', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Article' . "\0" . 'images'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Article $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getName(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName(string $name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription(string $description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getBarCode(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBarCode', []);

        return parent::getBarCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setBarCode(string $barCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBarCode', [$barCode]);

        return parent::setBarCode($barCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getInternalCode(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInternalCode', []);

        return parent::getInternalCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setInternalCode(string $internalCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInternalCode', [$internalCode]);

        return parent::setInternalCode($internalCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus(string $status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrice', []);

        return parent::getPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrice($price)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrice', [$price]);

        return parent::setPrice($price);
    }

    /**
     * {@inheritDoc}
     */
    public function getPriceCurrency(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPriceCurrency', []);

        return parent::getPriceCurrency();
    }

    /**
     * {@inheritDoc}
     */
    public function setPriceCurrency(string $priceCurrency)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPriceCurrency', [$priceCurrency]);

        return parent::setPriceCurrency($priceCurrency);
    }

    /**
     * {@inheritDoc}
     */
    public function getTax()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTax', []);

        return parent::getTax();
    }

    /**
     * {@inheritDoc}
     */
    public function setTax(\EventoOriginal\Core\Entities\Tax $tax)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTax', [$tax]);

        return parent::setTax($tax);
    }

    /**
     * {@inheritDoc}
     */
    public function getCostPrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCostPrice', []);

        return parent::getCostPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setCostPrice($costPrice)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCostPrice', [$costPrice]);

        return parent::setCostPrice($costPrice);
    }

    /**
     * {@inheritDoc}
     */
    public function getPublishedOn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPublishedOn', []);

        return parent::getPublishedOn();
    }

    /**
     * {@inheritDoc}
     */
    public function setPublishedOn(\DateTime $publishedOn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPublishedOn', [$publishedOn]);

        return parent::setPublishedOn($publishedOn);
    }

    /**
     * {@inheritDoc}
     */
    public function getIngredients()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIngredients', []);

        return parent::getIngredients();
    }

    /**
     * {@inheritDoc}
     */
    public function setIngredients(array $ingredients)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIngredients', [$ingredients]);

        return parent::setIngredients($ingredients);
    }

    /**
     * {@inheritDoc}
     */
    public function addIngredient(\EventoOriginal\Core\Entities\Ingredient $ingredient)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addIngredient', [$ingredient]);

        return parent::addIngredient($ingredient);
    }

    /**
     * {@inheritDoc}
     */
    public function getBrand(): \EventoOriginal\Core\Entities\Brand
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBrand', []);

        return parent::getBrand();
    }

    /**
     * {@inheritDoc}
     */
    public function setBrand(\EventoOriginal\Core\Entities\Brand $brand)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBrand', [$brand]);

        return parent::setBrand($brand);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategory(): \EventoOriginal\Core\Entities\Category
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategory', []);

        return parent::getCategory();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategory(\EventoOriginal\Core\Entities\Category $category)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategory', [$category]);

        return parent::setCategory($category);
    }

    /**
     * {@inheritDoc}
     */
    public function getTags()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTags', []);

        return parent::getTags();
    }

    /**
     * {@inheritDoc}
     */
    public function setTags(array $tags)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTags', [$tags]);

        return parent::setTags($tags);
    }

    /**
     * {@inheritDoc}
     */
    public function addTag(\EventoOriginal\Core\Entities\Tag $tag)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addTag', [$tag]);

        return parent::addTag($tag);
    }

    /**
     * {@inheritDoc}
     */
    public function getColors()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getColors', []);

        return parent::getColors();
    }

    /**
     * {@inheritDoc}
     */
    public function setColors(array $colors)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setColors', [$colors]);

        return parent::setColors($colors);
    }

    /**
     * {@inheritDoc}
     */
    public function addColor(\EventoOriginal\Core\Entities\Color $color)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addColor', [$color]);

        return parent::addColor($color);
    }

    /**
     * {@inheritDoc}
     */
    public function getFlavours()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFlavours', []);

        return parent::getFlavours();
    }

    /**
     * {@inheritDoc}
     */
    public function setFlavours(array $flavours)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFlavours', [$flavours]);

        return parent::setFlavours($flavours);
    }

    /**
     * {@inheritDoc}
     */
    public function addFlavour(\EventoOriginal\Core\Entities\Flavour $flavour)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addFlavour', [$flavour]);

        return parent::addFlavour($flavour);
    }

    /**
     * {@inheritDoc}
     */
    public function getAllergens()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAllergens', []);

        return parent::getAllergens();
    }

    /**
     * {@inheritDoc}
     */
    public function setAllergens(array $allergens)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAllergens', [$allergens]);

        return parent::setAllergens($allergens);
    }

    /**
     * {@inheritDoc}
     */
    public function addAllergen(\EventoOriginal\Core\Entities\Allergen $allergen)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAllergen', [$allergen]);

        return parent::addAllergen($allergen);
    }

    /**
     * {@inheritDoc}
     */
    public function getTranslations()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTranslations', []);

        return parent::getTranslations();
    }

    /**
     * {@inheritDoc}
     */
    public function addTranslation(\EventoOriginal\Core\Entities\ArticleTranslation $t)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addTranslation', [$t]);

        return parent::addTranslation($t);
    }

    /**
     * {@inheritDoc}
     */
    public function getSlug()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSlug', []);

        return parent::getSlug();
    }

    /**
     * {@inheritDoc}
     */
    public function setSlug(string $slug)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSlug', [$slug]);

        return parent::setSlug($slug);
    }

    /**
     * {@inheritDoc}
     */
    public function getImages()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImages', []);

        return parent::getImages();
    }

    /**
     * {@inheritDoc}
     */
    public function addImage(\EventoOriginal\Core\Entities\Image $images)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addImage', [$images]);

        return parent::addImage($images);
    }

    /**
     * {@inheritDoc}
     */
    public function setImages(array $images)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImages', [$images]);

        return parent::setImages($images);
    }

    /**
     * {@inheritDoc}
     */
    public function getLicenses()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLicenses', []);

        return parent::getLicenses();
    }

    /**
     * {@inheritDoc}
     */
    public function setLicense(\EventoOriginal\Core\Entities\License $license)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLicense', [$license]);

        return parent::setLicense($license);
    }

    /**
     * {@inheritDoc}
     */
    public function getShortDescription(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShortDescription', []);

        return parent::getShortDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setShortDescription(string $shortDescription)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShortDescription', [$shortDescription]);

        return parent::setShortDescription($shortDescription);
    }

    /**
     * {@inheritDoc}
     */
    public function getPricePerQuantity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPricePerQuantity', []);

        return parent::getPricePerQuantity();
    }

    /**
     * {@inheritDoc}
     */
    public function setPricePerQuantity(array $pricePerQuantity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPricePerQuantity', [$pricePerQuantity]);

        return parent::setPricePerQuantity($pricePerQuantity);
    }

}
