<?php

namespace DoctrineProxies\__CG__\EventoOriginal\Core\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Category extends \EventoOriginal\Core\Entities\Category implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'id', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Category' . "\0" . 'name', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Category' . "\0" . 'slug', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Category' . "\0" . 'description', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Category' . "\0" . 'translations', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Category' . "\0" . 'lft', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Category' . "\0" . 'level', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Category' . "\0" . 'rgt', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Category' . "\0" . 'root', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Category' . "\0" . 'parent', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Category' . "\0" . 'children', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Category' . "\0" . 'vouchers', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Category' . "\0" . 'affiliateCommission'];
        }

        return ['__isInitialized__', 'id', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Category' . "\0" . 'name', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Category' . "\0" . 'slug', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Category' . "\0" . 'description', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Category' . "\0" . 'translations', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Category' . "\0" . 'lft', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Category' . "\0" . 'level', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Category' . "\0" . 'rgt', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Category' . "\0" . 'root', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Category' . "\0" . 'parent', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Category' . "\0" . 'children', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Category' . "\0" . 'vouchers', '' . "\0" . 'EventoOriginal\\Core\\Entities\\Category' . "\0" . 'affiliateCommission'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Category $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getName(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName(string $name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getSlug()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSlug', []);

        return parent::getSlug();
    }

    /**
     * {@inheritDoc}
     */
    public function setSlug($slug)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSlug', [$slug]);

        return parent::setSlug($slug);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription(string $description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getTranslations()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTranslations', []);

        return parent::getTranslations();
    }

    /**
     * {@inheritDoc}
     */
    public function addTranslation(\EventoOriginal\Core\Entities\CategoryTranslation $t)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addTranslation', [$t]);

        return parent::addTranslation($t);
    }

    /**
     * {@inheritDoc}
     */
    public function getLft()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLft', []);

        return parent::getLft();
    }

    /**
     * {@inheritDoc}
     */
    public function getLevel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLevel', []);

        return parent::getLevel();
    }

    /**
     * {@inheritDoc}
     */
    public function getRgt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRgt', []);

        return parent::getRgt();
    }

    /**
     * {@inheritDoc}
     */
    public function getRoot()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoot', []);

        return parent::getRoot();
    }

    /**
     * {@inheritDoc}
     */
    public function getParent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParent', []);

        return parent::getParent();
    }

    /**
     * {@inheritDoc}
     */
    public function setParent(\EventoOriginal\Core\Entities\Category $parent)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParent', [$parent]);

        return parent::setParent($parent);
    }

    /**
     * {@inheritDoc}
     */
    public function getVouchers()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVouchers', []);

        return parent::getVouchers();
    }

    /**
     * {@inheritDoc}
     */
    public function setVouchers(array $vouchers)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVouchers', [$vouchers]);

        return parent::setVouchers($vouchers);
    }

    /**
     * {@inheritDoc}
     */
    public function addVoucher(\EventoOriginal\Core\Entities\Voucher $voucher)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addVoucher', [$voucher]);

        return parent::addVoucher($voucher);
    }

    /**
     * {@inheritDoc}
     */
    public function getChildren()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChildren', []);

        return parent::getChildren();
    }

    /**
     * {@inheritDoc}
     */
    public function setChildren(array $children)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setChildren', [$children]);

        return parent::setChildren($children);
    }

    /**
     * {@inheritDoc}
     */
    public function addChild(array $child)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addChild', [$child]);

        return parent::addChild($child);
    }

    /**
     * {@inheritDoc}
     */
    public function getAffiliateCommission()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAffiliateCommission', []);

        return parent::getAffiliateCommission();
    }

    /**
     * {@inheritDoc}
     */
    public function setAffiliateCommission(int $affiliateCommission)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAffiliateCommission', [$affiliateCommission]);

        return parent::setAffiliateCommission($affiliateCommission);
    }

}
